server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: currencyCalculationService
          uri: lb://currency-calculation-service/
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka